In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df_train = pd.read_csv('train_data.csv')
df_train.drop('id',axis=1,inplace=True)
df_test = pd.read_csv('test_data.csv')
df_test.drop('id',axis=1,inplace=True)
df_sample = pd.read_csv('sample_solution.csv')

In [3]:
df_train.head()

airline   flight source_city departure_time stops arrival_time  \
0   Vistara   UK-810   Bangalore  Early_Morning   one        Night   
1  SpiceJet  SG-5094   Hyderabad        Evening  zero        Night   
2   Vistara   UK-846   Bangalore        Morning   one      Evening   
3   Vistara   UK-706     Kolkata        Morning   one      Evening   
4    Indigo  6E-5394     Chennai  Early_Morning  zero      Morning   

  destination_city     class  duration  days_left  price  
0           Mumbai   Economy     14.25         21   7212  
1          Kolkata   Economy      1.75          7   5292  
2            Delhi  Business      9.58          5  60553  
3        Hyderabad   Economy      6.75         28   5760  
4           Mumbai   Economy      2.00          4  10712

In [4]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   airline           20000 non-null  object 
 1   flight            20000 non-null  object 
 2   source_city       20000 non-null  object 
 3   departure_time    20000 non-null  object 
 4   stops             20000 non-null  object 
 5   arrival_time      20000 non-null  object 
 6   destination_city  20000 non-null  object 
 7   class             20000 non-null  object 
 8   duration          20000 non-null  float64
 9   days_left         20000 non-null  int64  
 10  price             20000 non-null  int64  
dtypes: float64(1), int64(2), object(8)
memory usage: 1.7+ MB


In [5]:
df_train['stops'][df_train['stops']=='two_or_more'] = 'four'

In [6]:
def pre_prossesing(df):
  df['stops'] =df['stops'].map({'one':1,'zero':0,'four':4})
  df['arrival_time'] =df['arrival_time'].map({'Early_Morning':0,'Morning':1,'Afternoon':2,'Evening':4,'Night':5,'Late_Night':6})
  df['departure_time'] =df['departure_time'].map({'Early_Morning':0,'Morning':1,'Afternoon':2,'Evening':4,'Night':5,'Late_Night':6})
  df['source_city'] =df['source_city'].map({'Chennai':0,'Hyderabad':1,'Kolkata':2,'Bangalore':3,'Delhi':4,'Mumbai':5})
  df['destination_city'] =df['destination_city'].map({'Chennai':0,'Hyderabad':1,'Kolkata':2,'Bangalore':3,'Delhi':4,'Mumbai':5})
  df['class'] =df['class'].map({'Economy':0,'Business':1})
  df['airline'] =df['airline'].map({'SpiceJet':0,'AirAsia':1,'GO_FIRST':2,'Indigo':3,'Air_India':4,'Vistara':5})

  from sklearn.preprocessing import LabelEncoder
  le = LabelEncoder()
  df['flight'] = le.fit_transform(df['flight'])
  return df

In [7]:
df_train = pre_prossesing(df_train)

In [8]:
df_train.head()

airline  flight  source_city  departure_time  stops  arrival_time  \
0        5    1214            3               0      1             5   
1        0    1126            1               4      0             5   
2        5    1245            3               1      1             4   
3        5    1191            2               1      1             4   
4        3     275            0               0      0             1   

   destination_city  class  duration  days_left  price  
0                 5      0     14.25         21   7212  
1                 2      0      1.75          7   5292  
2                 4      1      9.58          5  60553  
3                 1      0      6.75         28   5760  
4                 5      0      2.00          4  10712

In [9]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   airline           20000 non-null  int64  
 1   flight            20000 non-null  int32  
 2   source_city       20000 non-null  int64  
 3   departure_time    20000 non-null  int64  
 4   stops             20000 non-null  int64  
 5   arrival_time      20000 non-null  int64  
 6   destination_city  20000 non-null  int64  
 7   class             20000 non-null  int64  
 8   duration          20000 non-null  float64
 9   days_left         20000 non-null  int64  
 10  price             20000 non-null  int64  
dtypes: float64(1), int32(1), int64(9)
memory usage: 1.6 MB


In [10]:
X = df_train.drop('price',axis=1)
y = df_train['price']

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X.values,y,test_size=0.2,random_state=12)

In [12]:
print("TRAIN DATA")
print(X_train.shape)
print(X_test.shape)

TRAIN DATA
(16000, 10)
(4000, 10)


In [13]:
print("TEST DATA")
print(X_test.shape)
print(y_test.shape)

TEST DATA
(4000, 10)
(4000,)


In [14]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
def p_score(model,X_train,y_train,X_test,y_test,train=True):

  if train:
    y_pred = model.predict(X_train)
    print("TRAIN")
    print('='*20)
    print("Mean absolute error: " ,mean_absolute_error(y_train,y_pred))
    print("Mean squared error: ", np.sqrt(mean_squared_error(y_train,y_pred)))
  else:
    y_pred = model.predict(X_test)
    print("TEST")
    print('='*20)
    print("Mean absolute error: " , mean_absolute_error(y_test,y_pred))
    print("Mean squared error: ", np.sqrt(mean_squared_error(y_test,y_pred)))

### Train

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import ExtraTreesRegressor

### LinearRegression

In [16]:
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [17]:
p_score(lr,X_train,y_train,X_test,y_test,train=True)

TRAIN
Mean absolute error:  4507.7955999763635
Mean squared error:  7223.783808688166


In [18]:
p_score(lr,X_train,y_train,X_test,y_test,train=False)

TEST
Mean absolute error:  4365.783088373729
Mean squared error:  7007.961147483976


### DecisionTreeRegressor

In [19]:
dt = DecisionTreeRegressor()
dt.fit(X_train,y_train)

DecisionTreeRegressor()

In [20]:
p_score(dt,X_train,y_train,X_test,y_test,train=True)

TRAIN
Mean absolute error:  0.1986875
Mean squared error:  10.934628194410635


In [21]:
p_score(dt,X_train,y_train,X_test,y_test,train=False)

TEST
Mean absolute error:  1938.22675
Mean squared error:  4502.13578507468


In [22]:
from sklearn.model_selection import cross_val_score

In [23]:
result = cross_val_score(dt,X_test,y_test,scoring='neg_mean_absolute_error',cv=5)
-result

array([2864.960625, 2860.895   , 3034.57    , 2804.8825  , 2864.5325  ])

In [24]:
-result.mean()

2885.968125

### RandomForestRegressor

In [25]:
rf = RandomForestRegressor()
rf.fit(X_train,y_train)

RandomForestRegressor()

In [26]:
p_score(rf,X_train,y_train,X_test,y_test,train=True)

TRAIN
Mean absolute error:  613.29736165625
Mean squared error:  1249.563440895615


In [27]:
p_score(rf,X_train,y_train,X_test,y_test,train=False)

TEST
Mean absolute error:  1684.634806875
Mean squared error:  3411.901056382847


In [28]:
result = cross_val_score(rf,X_test,y_test,scoring='neg_mean_absolute_error',cv=5)
-result

array([2258.10215312, 2393.70766875, 2237.51152313, 2492.03033125,
       2288.0263375 ])

In [29]:
-result.mean()

2333.87560275

### ExtraTreesRegressor

In [30]:
extree = ExtraTreesRegressor()
extree.fit(X_train,y_train)

ExtraTreesRegressor()

In [31]:
p_score(extree,X_train,y_train,X_test,y_test,train=True)

TRAIN
Mean absolute error:  0.2014987500000003
Mean squared error:  10.937495788570619


In [32]:
p_score(extree,X_train,y_train,X_test,y_test,train=False)

TEST
Mean absolute error:  1658.04350625
Mean squared error:  3462.900265300649


In [33]:
result = cross_val_score(extree,X_test,y_test,scoring='neg_mean_absolute_error',cv=5)
-result

array([2245.71898125, 2386.40065   , 2301.821     , 2502.80405   ,
       2363.6703    ])

In [34]:
-result.mean()

2360.08299625

### Test

In [35]:
df_test.sample(5)

airline   flight source_city departure_time stops arrival_time  \
1548  GO_FIRST  G8-7556   Hyderabad      Afternoon   one        Night   
1115  GO_FIRST   G8-323       Delhi        Evening   one   Late_Night   
3173   Vistara   UK-910      Mumbai        Evening   one        Night   
590   GO_FIRST   G8-320   Bangalore        Evening   one      Morning   
4005   AirAsia  I5-2461     Chennai        Evening   one      Morning   

     destination_city    class  duration  days_left  
1548          Kolkata  Economy      6.25         43  
1115        Bangalore  Economy      5.75         33  
3173          Kolkata  Economy      5.17         32  
590             Delhi  Economy     14.17          5  
4005            Delhi  Economy     17.83         45

In [36]:
df_test['stops'][df_test['stops']=='two_or_more'] = 'four'

In [37]:
df_test = pre_prossesing(df_test)

In [38]:
df_test.sample()

airline  flight  source_city  departure_time  stops  arrival_time  \
1073        5     845            4               5      4             1   

      destination_city  class  duration  days_left  
1073                 0      0     15.17         11

In [39]:
y_predict = rf.predict(df_test.values)

In [40]:
y_predict[:10]

array([46308.95, 45100.94, 25435.15,  5561.63,  6442.01,  5900.04,
        4518.78, 13993.29,  5285.02, 22283.37])

In [41]:
df_sample['price'] = y_predict

In [42]:
df_sample.head(10)

id     price
0   1  46308.95
1   2  45100.94
2   3  25435.15
3   4   5561.63
4   5   6442.01
5   6   5900.04
6   7   4518.78
7   8  13993.29
8   9   5285.02
9  10  22283.37

In [44]:
df_sample.to_csv('sample.csv',index=False)